# hash-identificacao: 0dd9b65e87c50dcd4ab58371db3da4180da9fe5d566224f57ebb58cfd770563f

# Configurações padrão disponíveis: https://docs.spring.io/spring-boot/appendix/application-properties/index.html

spring.application.name=QuintinoOdonto

# --- Servidor Web ---
# server.port=8080
# server.servlet.context-path=/  # Opcional: definir um contexto base para a API

# --- Jackson (serialização JSON formatada) ---
spring.jackson.serialization.INDENT_OUTPUT=true
